### ISSUE TITLE
Sleep still not working 6.0

### ISSUE THREAD

**Issue by UseAfterMe** [jakibaki/sys-netcheat#22]
release 1.3.3
sleep still not working, black screen only action is hard reboot.

**Comment by jakibaki** [comment]
Uhm, that's weird.

Are you sure that you properly removed fullsvcperm and enabled exosphere in you netcheat-profile?

**Comment by UseAfterMe** [comment]
positive:
{---- sys-netcheat ----}
[CFW + sys-netcheat]
kip1=modules/newfirm/loader.kip
kip1=modules/newfirm/sm.kip
kip1=modules/newfirm/pm.kip
kip1=modules/sys-netcheat.kip
secmon=modules/atmosphere/exosphere.bin
kip1patch=nosigchk
debugmode=1
[LayeredFS + sys-netcheat]
kip1=modules/newfirm/loader.kip
kip1=modules/newfirm/sm.kip
kip1=modules/newfirm/fs_mitm.kip
kip1=modules/newfirm/pm.kip
kip1=modules/sys-netcheat.kip
secmon=modules/atmosphere/exosphere.bin
atmosphere=1
kip1patch=nosigchk
debugmode=1
[Stock + sys-netcheat]
kip1=modules/sys-netcheat.kip
debugmode=1
{ }

**Comment by jakibaki** [comment]
Hm, that's weird.

Worked perfectly for the person testing it for me (I don't have an 6.0 switch right now).

That person was using the latest git build of atmosphere though so it might be a problem with exosphere that will maybe be fixed with the next sdfiles release.

**Comment by UseAfterMe** [comment]
I Just compiled the latest exosphere and the sleep bug is still there.
This only happens with sys-netcheat or me, layerfs or just cfw mode no sleep mode bug at all.

**Comment by jakibaki** [comment]
The only difference that I can see between your and the testers setup is that you're might not be using layeredfs (which I don't think should be a problem but I'm out of ideas).

If you haven't already could you please check if the sys-netcheat + layeredfs profile works?

**Comment by UseAfterMe** [comment]
Tested with layered as well, still not working.

**Comment by rickyyip25** [comment]
Same issue here, although I have fullsvcperm enabled. I'm using SDFiles v9.0.4.

**Comment by AnnsAnns** [comment]
This is something that was caused by fw6.0 - Try updating to 6.0.1 and test it again! @evilsperm @metacoz

**Comment by UseAfterMe** [comment]
6.0.1 still a no go

**Comment by rickyyip25** [comment]
@tumGER I will test it ASAP. Is 6.0.1 compatible with ReiNX or atmosphere tho?

**Comment by AnnsAnns** [comment]
What a weird bug - If somebody finds easily reproducible steps please post them!

@metacoz ReiNX probably will struggle with support, just use the "more configs > sys-netcheat" options from v9.0.4

**Comment by rickyyip25** [comment]
Thanks for the suggestions @tumGER

**Comment by rickyyip25** [comment]
@tumGER So I have upgraded to 6.0.1, but the issue seems to stay.
The sys-netcheat.kip is from the 1.3.3 release. All the other files are from SDFiles v9.0.4.
Here is my config in hekate_ipl.ini that I used:

```
[CFW + netcheat]
secmon=modules/atmosphere/exosphere.bin
kip1=modules/newfirm/loader.kip
kip1=modules/newfirm/sm.kip
kip1=modules/newfirm/pm.kip
kip1=modules/sys-netcheat.kip
kip1patch=nosigchk
debugmode=1
{ }
```

Also, I tried adding LayeredFS (fs_mitm.kip) to the config but no luck.

**Comment by AnnsAnns** [comment]
Hmm, there is really nothing we can do until someone finds a way to reproduce it

**Comment by rickyyip25** [comment]
@tumGER Is there an example set of config and files that is proved to be working? If that works on our switch then we can better locate the problem.

**Comment by AnnsAnns** [comment]
Hmm, v9.0.4 worked for me

Try testing with this: [test-sdfiles.zip](https://github.com/jakibaki/sys-netcheat/files/2476660/test-sdfiles.zip)

Does this work? @evilsperm @metacoz

**Comment by rickyyip25** [comment]
@tumGER It does not seem to solve the problem either. Another thing is that LayeredFS+sys-netcheat could not boot.

**Comment by AnnsAnns** [comment]
Okay, I'm giving up - No idea how to fix that

**Comment by rickyyip25** [comment]
@tumGER Thanks anyways. sys-netcheat is quite amazing for how it works. It is just this annoying bug that makes me either keep the switch on while netcheat is loaded, or reboot the switch every time I have finished using it.  
I will post follow-ups if there is finally a solution.

**Comment by jakibaki** [comment]
I think I know the problem!

You need the `atmosphere=1` flag in your profile.

**Comment by rickyyip25** [comment]
@jakibaki I have tried it again and sleep mode still does not work.
I believe it could be an issue with debug mode on hekate: [https://github.com/CTCaer/hekate/issues/119](https://github.com/CTCaer/hekate/issues/119)

**Comment by jakibaki** [comment]
>I believe it could be an issue with debug mode on hekate: CTCaer/hekate#119

That issue is supposed to be solved by using exosphere.

**Comment by rickyyip25** [comment]
I have just updated to SDFiles v10, the problem still exists but I wanna add more info to that.
If I use the default [CFW + sys-netcheat] config, my switch would not boot and get stuck at the booting logo screen.
My switch can only boot with sys-netcheat loaded WITHOUT loading "fs-mitm.kip".
When it boots with sys-netcheat loaded, sys-netcheat works like it should. However, once it attempts to enter sleep mode, it cannot be woken up again.

Current switch version: 6.0.1 (upgraded from 3.0.2 -> 6.0.0 -> 6.0.1, after restored raw NAND backup before each upgrade). The raw NAND dump was made in ReiNX Toolkit, but I am not using ReiNX anymore.
Using AutoRCM in Hekate.

Any idea?

**Comment by mikeguidry** [comment]
On newest SD files with hekate 4.2 it doesn't wake up from sleep ever... 6.1.0 w/AutoCRM

**Comment by buitim** [comment]
Reproduced on my end using the latest SDFiles/Kosmos and [CFW + sys-netcheat] config on 6.0.0. Using Hekate AutoRCM. Switch boots up and everything works perfectly. However, once I put the device to sleep, it will not wake up again unless I force shutdown and reinject the payload. Sleep properly works with Kosmos' [CFW + sys-ftpd] config.

**Comment by OnkelM** [comment]
same here too, no sleep with sys-netcheat enabled

**Comment by sonicwolfsdutch** [comment]
same here running on firmware 5.1 sd filles 11.1 i launch it loaded black screen did it a second time loaded and switch logo and black screen using autorcm atm

**Comment by jakibaki** [comment]
https://github.com/Atmosphere-NX/Atmosphere/commit/a79f4cf6f6ecef2f17da43ca9cca2225e0949e7f

:)

**Comment by buitim** [comment]
ooohhhh yessss... Just in time for winter break :)
@jakibaki you have any idea where one could grab nightlies for Atmosphere? Or should we wait for an official release? Excited to test this and see if it works

EDIT: [Checked here](https://jenkins.lavatech.top/job/atmosphere/) but it looks like the builds are failing.
EDIT 2: Got the latest Kosmos release and it currently hangs on the Switch splash screen. [Issue opened here.](https://github.com/AtlasNX/Kosmos/issues/161)

**Comment by thomIeg50** [comment]
this have issue with me !

**Comment by ThatNerdyPikachu** [comment]
i too have the issue with !

**Comment by thomIeg50** [comment]
you are aware @jakibaki this not alone issue ?

**Comment by ThatNerdyPikachu** [comment]
i cannot sleep while cheat vroom in night sky :/

**Comment by simontime** [comment]
![image](https://user-images.githubusercontent.com/40786398/50135360-06b98300-02e8-11e9-9e25-e9bc2caf9cfd.png)

**Comment by thomIeg50** [comment]
please @ThatNerdyPikachu thank you for proof not alone issue !
do have that ?

**Comment by thomIeg50** [comment]
?

**Comment by thomIeg50** [comment]
@ThatNerdyPikachu do have proof of issue ?

**Comment by thomIeg50** [comment]
hello ?

**Comment by jakibaki** [comment]
Finally got around "fixing" that (aka finally making sys-netcheat run at all with current atmos which already has a debugmode-sleep-fix) in release 1.3.4 :)

**Comment by buitim** [comment]
Works perfectly @jakibaki! Thank you so much for your hard work! Really appreciate it man 🙏
